# -*- coding: utf-8 -*-
"""Day-3-Assignment.ipynb

Automatically generated by Colaboratory.


Question 1: Answer
"""

a= 5+5j
b=6+3j
c=a-b
print(c)

"""Question 2: Answer"""

import math
a=math.sqrt(math.sqrt(81))
print(a)

"""Question 3: Answer"""

a=10
b=20
c=b
b=a
a=c
print(a)
print(b)

"""Question 4: Answer"""

a=35
b=50
a,b=b,a
print(a)
print(b)

"""Question 5: Answer"""

Farenheit_degree = 90
celsius_C =(( Farenheit_degree - 32)*(5/9))
print('Celsius is',celsius_C)
kelvin_K = celsius_C + 273.15
print('Kelvin is',kelvin_K)

"""Question 6: Answer"""

a= 5
type(a)

a= 3.45
type(a)

a='hello'
type(a)

a=10
a==20

a=['c','g',2,4.5]
type(a)

a=('c','g',2,4.5)
type(a)

a={b:20, c:30}
type(a)
